FROM node:18-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR '/home/node/app'

# The dot ( . ) below  means copy file to WORKDIR
COPY --chown=node:node ./package.json ./
RUN npm install

COPY --chown=node:node . .

#CMD ["npm", "start"]
CMD ["npm", "run", "start"]